title: BoookBasket
author: Triasa
email: triasamunshi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog talks about books.

# social links
twitter_username: triasa_13
github_username:  triasa5

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
